#!/usr/bin/env bash
#Depending on iteration print bad luck, good luck or Best School
i="1"
while [ $i -le 10 ]
do
	if [ $i = 4 ]; then
		echo "bad luck"
	elif [ $i = 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$(( i+1 ))
done
