#!/usr/bin/env bash
# Display the time for 12 hours and 59 minutes
hour="0"
while [ $hour -le 12 ]; do
	echo "Hour: $hour"	
	min="1"	
	while [ $min -lt 60 ]; do
		echo "$min"
		min=$(( min+1 ))
	done
	hour=$(( hour+1 ))
done
